import type { StoreSettings } from "@/types/store";

export const defaultStoreSettings: StoreSettings = {
  storeName: "الون استایل",
  announcement: "ارسال رایگان برای سفارش‌های بالای ۵ میلیون تومان",
  supportPhone: "09914534178",
  address: "قم، بلوار الغدیر، روبروی شهرک قدس، جنب سینمای ونوس",
  shippingCost: 130_000,
  freeShippingThreshold: 5_000_000,
  instagram: "elevenstyle.ir",
  heroTitle: "کالکشن تازه، استایل تازه",
  heroSubtitle: "انتخاب‌های جدید برای مردانی که متفاوت دیده می‌شوند.",
  heroImage: "https://elevenstyle.ir/wp-content/uploads/2026/09/Tshirtfallbannerdesktop-scaled.webp",
  heroMobileImage: "https://elevenstyle.ir/wp-content/uploads/2026/09/tshirtfallbannermobile-1.webp",
  heroEyebrow: "انتخاب تازه ادیتورها",
  heroPrimaryCta: "خرید کالکشن",
  storyTitle: "لباس‌هایی برای هر روز؛ جزئیاتی برای متفاوت‌بودن.",
  editorialTitle: "کمتر انتخاب کن، بهتر ست کن.",
  editorialText: "یک کمد حساب‌شده با رنگ‌های خنثی و برش‌های درست؛ قطعه‌هایی که از صبح تا شب کنار هم کار می‌کنند.",
  showNewArrivals: true,
  showCategories: true,
  showEditorial: true,
  showBestSellers: true,
  showSaleProducts: true,
  showFestival: true,
  festivalEyebrow: "COLOR FEST / جشنواره رنگ",
  festivalTitle: "فصل تازه را رنگی شروع کن.",
  festivalSubtitle: "انتخاب‌های محدود جشنواره با رنگ‌های گرم، خنثی و پاستلی برای ساختن یک استایل تازه.",
  festivalImage: "https://elevenstyle.ir/wp-content/uploads/2026/09/Shirt.webp",
  monthlySalesTarget: 500_000_000,
  announcementEnabled: true,
  seoTitle: "الون استایل | فروشگاه پوشاک مردانه",
  seoDescription: "خرید آنلاین پوشاک، کفش و اکسسوری مردانه از الون استایل با ارسال به سراسر ایران.",
  footerDescription: "در الون استایل، لباس فقط یک انتخاب نیست؛ بخشی از اعتمادبه‌نفس و سبک زندگی شماست. مجموعه‌ای منتخب از پوشاک مردانه با طراحی روز و کیفیت ماندگار.",
  footerCopyright: "© ۱۴۰۵ الون استایل؛ تمامی حقوق محفوظ است.",
  footerTagline: "تجربه‌ای مدرن برای خرید پوشاک مردانه",
  newArrivalsEyebrow: "JUST IN / تازه رسیده",
  newArrivalsTitle: "اولین نفر باش که می‌پوشد",
  categoriesEyebrow: "SHOP BY MOOD",
  categoriesTitle: "از حال‌وهوایت شروع کن",
  categoriesDescription: "دسته‌بندی‌هایی که هر کدام یک استایل کامل را می‌سازند.",
  saleEyebrow: "SALE / تخفیف‌های فعال",
  saleTitle: "انتخاب‌های خوش‌قیمت این هفته",
  editorialEyebrow: "راهنمای استایل",
  editorialCta: "دیدن این انتخاب",
  bestSellersEyebrow: "BEST SELLERS",
  bestSellersTitle: "انتخاب‌های امتحان‌پس‌داده",
  festivalCta: "ورود به جشنواره",
  relatedEyebrow: "پیشنهاد برای شما",
  relatedTitle: "محصولات مشابه",
  trustShippingTitle: "ارسال سریع",
  trustShippingText: "تحویل امن به سراسر ایران",
  trustReturnTitle: "ضمانت بازگشت",
  trustReturnText: "تا ۷ روز پس از تحویل",
  trustQualityTitle: "خرید مطمئن",
  trustQualityText: "تضمین اصالت و کیفیت کالا",
  trustSupportTitle: "پشتیبانی واقعی",
  trustSupportText: "همراه شما پیش و پس از خرید",
  themeBrand: "#8f4d59",
  themeBrandDark: "#6c3640",
  themeInk: "#2c2825",
  themeBackground: "#fffdfb",
  themeSurface: "#fbf7f3",
  themeBorder: "#e8d9cf",
  themeMint: "#b6dfd8",
  themeBlush: "#e8c7d7",
  lowStockThreshold: 5,
  navigationItems: [
    { id: "nav-tshirt", label: "تیشرت", mode: "category", target: "tshirt", fallbackSlug: "men-t-shirts-and-sweatshirts", active: true },
    { id: "nav-jogger", label: "شلوار اسلش", mode: "search", target: "اسلش", fallbackSlug: "men-pants", active: true },
    { id: "nav-mom", label: "شلوار مام فیت", mode: "search", target: "مام", fallbackSlug: "men-pants", active: true },
    { id: "nav-baggy", label: "شلوار بگ", mode: "search", target: "بگ", fallbackSlug: "men-pants", active: true },
    { id: "nav-hoodie", label: "هودی و سوییشرت", mode: "category", target: "men-sweatshirts-and-hoodies", fallbackSlug: "men-sweatshirts-and-hoodies", active: true },
    { id: "nav-set", label: "ست مردانه", mode: "category", target: "men-set", fallbackSlug: "men-set", active: true },
    { id: "nav-shoes", label: "کتونی", mode: "category", target: "men-shoes-and-boots", fallbackSlug: "men-shoes-and-boots", active: true },
    { id: "nav-dors", label: "دورس", mode: "search", target: "دورس", fallbackSlug: "men-sweatshirts-and-hoodies", active: true },
  ],
  homeSectionOrder: ["new", "sale", "categories", "festival", "editorial", "best", "trust"],
};
