import { Banknote, Eye, PackageCheck, Search, ShoppingBag, Truck } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/Field";
import { Modal } from "@/components/ui/Modal";
import { orderStatusClass, orderStatusLabels, paymentStatusLabels } from "@/lib/admin";
import { formatDate, formatToman, toFa } from "@/lib/format";
import { useStore } from "@/store/use-store";
import type { Order, OrderStatus } from "@/types/store";

const statuses = Object.entries(orderStatusLabels) as [OrderStatus, string][];

export function AdminOrdersPage() {
  const orders = useStore((state) => state.orders);
  const updateStatus = useStore((state) => state.updateOrderStatus);
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("all");
  const [selected, setSelected] = useState<Order | null>(null);
  const filtered = useMemo(() => { const term = query.trim().toLowerCase(); return orders.filter((order) => (!term || `${order.id} ${order.customerName} ${order.phone}`.toLowerCase().includes(term)) && (status === "all" || order.status === status)); }, [orders, query, status]);
  const revenue = orders.filter((item) => item.status !== "cancelled").reduce((sum, item) => sum + item.total, 0);
  const active = orders.filter((item) => ["pending", "processing", "shipped"].includes(item.status)).length;

  function changeStatus(id: string, value: OrderStatus) { updateStatus(id, value); setSelected((current) => current?.id === id ? { ...current, status: value } : current); toast.success("وضعیت سفارش به‌روز شد"); }

  return (
    <div className="mx-auto max-w-[1500px] space-y-6"><div><p className="text-[10px] font-bold text-brand">فروش و ارسال</p><h1 className="mt-1 text-2xl font-black">مدیریت سفارش‌ها</h1><p className="mt-1.5 text-[10px] text-muted">سفارش‌ها را بررسی کنید و وضعیت آماده‌سازی و ارسال را تغییر دهید.</p></div>
      <section className="grid gap-3 sm:grid-cols-3">{[[ShoppingBag, "کل سفارش‌ها", `${toFa(orders.length)} سفارش`, "bg-blue-50 text-blue-700"], [Truck, "در جریان", `${toFa(active)} سفارش`, "bg-amber-50 text-amber-700"], [Banknote, "فروش ثبت‌شده", formatToman(revenue), "bg-emerald-50 text-emerald-700"]].map(([Icon, label, value, tone]) => { const I = Icon as typeof ShoppingBag; return <article key={String(label)} className="flex items-center gap-4 rounded-2xl border border-black/5 bg-white p-4"><span className={`grid size-11 place-items-center rounded-xl ${tone}`}><I className="size-5" /></span><div><strong className="text-sm font-black">{String(value)}</strong><p className="mt-1 text-[9px] text-muted">{String(label)}</p></div></article>; })}</section>
      <section className="overflow-hidden rounded-2xl border border-black/5 bg-white"><div className="flex flex-col gap-3 border-b border-border p-4 sm:flex-row sm:items-center sm:justify-between"><div className="relative w-full sm:max-w-sm"><Search className="absolute right-3 top-1/2 size-4 -translate-y-1/2 text-muted" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="شماره سفارش، مشتری یا موبایل..." className="bg-stone-50 pr-10" /></div><select value={status} onChange={(event) => setStatus(event.target.value)} className="h-11 rounded-xl border border-border bg-white px-3 text-[10px] font-bold outline-none"><option value="all">همه وضعیت‌ها</option>{statuses.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>
        <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-right text-[9px]"><thead className="bg-stone-50 text-muted"><tr><th className="px-5 py-3 font-medium">سفارش</th><th className="px-3 py-3 font-medium">مشتری</th><th className="px-3 py-3 font-medium">تاریخ</th><th className="px-3 py-3 font-medium">اقلام</th><th className="px-3 py-3 font-medium">مبلغ</th><th className="px-3 py-3 font-medium">وضعیت</th><th className="px-5 py-3 font-medium">جزئیات</th></tr></thead><tbody className="divide-y divide-border">{filtered.map((order) => <tr key={order.id} className="hover:bg-stone-50/70"><td className="px-5 py-3.5 font-black" dir="ltr">{order.id}</td><td className="px-3 py-3.5"><strong className="block text-[10px]">{order.customerName}</strong><span className="text-[8px] text-muted" dir="ltr">{order.phone}</span></td><td className="px-3 py-3.5 text-muted">{formatDate(order.createdAt)}</td><td className="px-3 py-3.5">{toFa(order.items.reduce((sum, item) => sum + item.quantity, 0))} قلم</td><td className="px-3 py-3.5 font-bold">{formatToman(order.total)}</td><td className="px-3 py-3.5"><select value={order.status} onChange={(event) => changeStatus(order.id, event.target.value as OrderStatus)} className={`h-8 rounded-full border-0 px-2 text-[8px] font-bold outline-none ring-1 ring-inset ${orderStatusClass[order.status]}`}>{statuses.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></td><td className="px-5 py-3.5"><Button size="sm" variant="ghost" onClick={() => setSelected(order)} className="h-8 text-[9px]"><Eye className="size-3.5" />مشاهده</Button></td></tr>)}</tbody></table></div>
        {!filtered.length && <p className="py-16 text-center text-xs text-muted">سفارشی پیدا نشد.</p>}<div className="border-t border-border px-5 py-3 text-[9px] text-muted">نمایش {toFa(filtered.length)} سفارش</div>
      </section>
      <Modal open={Boolean(selected)} onClose={() => setSelected(null)} title={`جزئیات سفارش ${selected?.id || ""}`} description={selected ? formatDate(selected.createdAt) : ""}>
        {selected && <div className="space-y-6 p-5 sm:p-6"><div className="grid gap-3 rounded-xl bg-stone-50 p-4 text-[10px] sm:grid-cols-2"><div><span className="text-muted">مشتری</span><strong className="mt-1 block text-xs">{selected.customerName}</strong><span className="mt-1 block text-muted" dir="ltr">{selected.phone}</span></div><div><span className="text-muted">نشانی ارسال</span><p className="mt-1 leading-6">{selected.address}</p></div></div><div><label className="mb-2 block text-[10px] font-bold">وضعیت سفارش</label><select value={selected.status} onChange={(event) => changeStatus(selected.id, event.target.value as OrderStatus)} className="h-11 w-full rounded-xl border border-border px-3 text-xs outline-none">{statuses.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div><h3 className="text-[10px] font-black">اقلام سفارش</h3><ul className="mt-3 divide-y divide-border rounded-xl border border-border px-4">{selected.items.map((item, index) => <li key={`${item.productId}-${index}`} className="flex justify-between gap-4 py-3 text-[10px]"><span>{item.name} × {toFa(item.quantity)}<small className="mt-1 block text-muted">{item.size} / {item.color}</small></span><strong className="shrink-0">{formatToman(item.price * item.quantity)}</strong></li>)}</ul></div><dl className="divide-y divide-border rounded-xl border border-border px-4 text-[10px]"><div className="flex justify-between py-3"><dt className="text-muted">وضعیت پرداخت</dt><dd className="font-bold">{paymentStatusLabels[selected.paymentStatus]}</dd></div><div className="flex justify-between py-3"><dt className="text-muted">روش ارسال</dt><dd className="font-bold">{selected.shippingMethod}</dd></div><div className="flex justify-between py-3 text-xs"><dt className="font-black">مبلغ کل</dt><dd className="font-black">{formatToman(selected.total)}</dd></div></dl><Button className="w-full" onClick={() => changeStatus(selected.id, selected.status === "pending" ? "processing" : "shipped")} disabled={["delivered", "cancelled"].includes(selected.status)}><PackageCheck className="size-4" />ثبت مرحله بعد سفارش</Button></div>}
      </Modal>
    </div>
  );
}
